name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - pip:
    - scipy
    - matplotlib
    - IPython
    - ipywidgets
    - latex
    - jupyterlab_latex
    - voila
